import { atom } from 'jotai'

export const slideIndexAtom = atom(0)
export const isTransitioningAtom = atom(false)
export const hasEnteredAtom = atom(false)

export const slides = [
  {
    id: 'paddle-surf',
    time: '10:30 AM',
    title: 'PADDLE\nSURF',
    description: 'Glide across tranquil waters',
    temp: '22°',
    condition: 'glossy waters',
    location: 'Southern Lagoon Beach',
    stationName: 'Station Lighthouse',
    cardColor: '#6C4CE8',
    circleColor: '#F5C518',
    description2: 'Glide gracefully along scenic shorelines while building balance and taking in serene ocean views.',
    image: '/images/paddle.webp',
    gearImage: '/images/bg-paddle2.webp',
    effect: 'splash',
  },
  {
    id: 'kite-boarding',
    time: '02:15 PM',
    title: 'KITE\nBOARDING',
    description: 'Catch the wind and ride high',
    temp: '27°',
    condition: 'gusty winds',
    location: 'Breeze Point Bay',
    stationName: 'Station Watchtower',
    cardColor: '#4C6FE8',
    circleColor: '#abcfb0',
    description2: 'Harness the power of strong coastal winds to launch high jumps and skim across open waters.',
    image: '/images/kite.webp',
    gearImage: '/images/bg-para.webp',
    effect: 'wind',
  },
  {
    id: 'wind-surfing',
    time: '07:00 AM',
    title: 'WIND\nSURFING',
    description: 'Ride the offshore coastal gusts',
    temp: '24°',
    condition: 'side-shore wind',
    location: 'North Bay Cove',
    stationName: 'Station Pier',
    cardColor: '#00A896',
    circleColor: '#8d83be',
    description2: 'Master the elements as you carve through gentle swells powered by steady morning breezes.',
    image: '/images/windsurf.webp',
    gearImage: '/images/bg-surf.webp',
    effect: 'wind',
  },
  {
    id: 'scuba-diving',
    time: '01:15 PM',
    title: 'SCUBA\nDIVING',
    description: 'Discover underwater reef life',
    temp: '20°',
    condition: 'high visibility',
    location: 'Coral Shoals',
    stationName: 'Station Reef',
    cardColor: '#028090',
    circleColor: '#8d83be',
    description2: 'Descend into crystal-clear depths to explore vibrant coral ecosystems and marine life up close.',
    image: '/images/scuba.webp',
    gearImage: '/images/bg-scuba.webp',
    effect: 'bubbles',
  },
  {
    id: 'sea-kayaking',
    time: '04:45 PM',
    title: 'SEA\nKAYAKING',
    description: 'Navigate coastal sea caves',
    temp: '25°',
    condition: 'calm swell',
    location: 'Emerald Cliff Cove',
    stationName: 'Station Harbour',
    cardColor: '#05668D',
    circleColor: '#70058d',
    description2: 'Paddle through hidden sea caverns and steep limestone cliffs along picturesque coastlines.',
    image: '/images/kayaking.webp',
    gearImage: '/images/bg-kayak.webp',
    effect: 'ripple',
  },
]