/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/couch.glb --transform --output src/components/models/Couch.jsx 
Files: public/models/couch.glb [2.16MB] > C:\Users\G\Desktop\beach store\src\components\models\couch-transformed.glb [234.45KB] (89%)
Author: PupUpProductions (https://sketchfab.com/PupUpProductions)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylised-scandi-couch-with-throw-c3db74f2d7b94bcfb0ebbe170b04ea9d
Title: Stylised scandi couch with throw
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Couch(props) {
  const { nodes, materials } = useGLTF('./models/couch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_low_CouchMat_0.geometry} material={materials.CouchMat} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/couch-transformed.glb')
