/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flower_pot.glb --transform --output src/components/models/FlowerPot.jsx 
Files: public/models/flower_pot.glb [9.12MB] > C:\Users\G\Desktop\beach store\src\components\models\flower_pot-transformed.glb [849.43KB] (91%)
Author: Jelvehkar (https://sketchfab.com/alihoseini13000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-pot-f960fa7dce8642848ed211e3c01ad976
Title: flower pot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FlowerPot(props) {
  const { nodes, materials } = useGLTF('./models/flower_pot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials['02_-_Default']} position={[0, 1.144, -0.4]} scale={6.919} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.GOLDAN} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.KHAK} />
    </group>
  )
}

useGLTF.preload('./models/flower_pot-transformed.glb')
